Make the package executable.
Use `click` to define the CLI, rephrasing the existing `sign.py` and
`verify.py` scripts.

With `click`, rather than `argparse` we have the option to nest multiple
subcommands (one level for sign/verify, one level for PKI method) and we
have the option to make one command be the default (Sigstore signing).
This was claimed to be possible with `argparse` when the initial
`sign.py`/`verify.py` scripts were created but it never worked.

Since all options are now defined in the same file, it is easy to keep
them in sync as we clean-up the code. There are already some TODOs added
in this PR as the non-Sigstore API uses strings instead of
`pathlib.Path`, which will also impact #148.

This should fix #330.

Tested via signing a model with all 3 modes and verifying the Sigstore
signature, after first building a wheel and installing it in an
environment:

```console
[...]$ python -m model_signing sign ${MODEL}
[...]
[...]$ python -m model_signing sign sigtore ${MODEL}
[...]
[...]$ python -m model_signing sign key ${MODEL} --private_key ${KEY}
[...]
[...]$ python -m model_signing sign certificate ${MODEL} \
  --private_key ${KEY} --signing_certificate ${CERT}
[...]
[...]$ python -m model_signing verify ${MODEL} \
  --signature ${SIGNATURE} \
  --identity ${IDENTITY} --identity_provider ${OIDC_PROVIDER}
```

Tested that the help option works, either directly or implicitly:

```console
[...]$ python -m model_signing
Usage: python -m model_signing [OPTIONS] COMMAND [ARGS]...

  ML model signing and verification.

  Use each subcommand's `--help` option for details on each mode.

Options:
  --version   Show the version and exit.
  -h, --help  Show this message and exit.

Commands:
  sign    Sign models.
  verify  Verify models.

  Check https://sigstore.github.io/model-transparency for documentation and
  more details.
[...]$ python -m model_signing -h
Usage: python -m model_signing [OPTIONS] COMMAND [ARGS]...

  ML model signing and verification.

  Use each subcommand's `--help` option for details on each mode.

Options:
  --version   Show the version and exit.
  -h, --help  Show this message and exit.

Commands:
  sign    Sign models.
  verify  Verify models.

  Check https://sigstore.github.io/model-transparency for documentation and
  more details.
[...]$ python -m model_signing --help
Usage: python -m model_signing [OPTIONS] COMMAND [ARGS]...

  ML model signing and verification.

  Use each subcommand's `--help` option for details on each mode.

Options:
  --version   Show the version and exit.
  -h, --help  Show this message and exit.

Commands:
  sign    Sign models.
  verify  Verify models.

  Check https://sigstore.github.io/model-transparency for documentation and
  more details.
```

It also works for the subcommands:

```console
[...]$ python -m model_signing sign
Usage: python -m model_signing sign [OPTIONS] PKI_METHOD

  Sign models.

  Produces a cryptographic signature (in the form of a Sigstore bundle) for a
  model. We support any model format, either as a single file or as a
  directory.

  We support multiple PKI methods, specified as subcommands. By default, the
  signature is generated via Sigstore (as if invoking `sigstore` subcommand).

  Use each subcommand's `--help` option for details on each mode.

Options:
  -h, --help  Show this message and exit.

Commands:
  certificate  Sign using a certificate.
  key          Sign using a private key (paired with a public one).
  sigstore     Sign using Sigstore (DEFAULT signing method).
[...]$ python -m model_signing sign sigstore -h
Usage: python -m model_signing sign sigstore [OPTIONS] MODEL_PATH

  Sign using Sigstore (DEFAULT signing method).

  Signing the model at MODEL_PATH, produces the signature at SIGNATURE_PATH
  (as per `--signature` option).

  If using Sigstore, we need to provision an OIDC token. In general, this is
  taken from an interractive OIDC flow, but ambient credentials could be used
  to use workload identity tokens (e.g., when running in GitHub actions).
  Alternatively, a constant identity token can be provided via
  `--identity_token`.

  Sigstore allows users to use a staging instance for test-only signatures.
  Passing the `--use_staging` flag would use that instance instead of the
  production one.

Options:
  --signature SIGNATURE_PATH  Location of the signature file to generate.
                              Defaults to `model.sig`.
  --use_ambient_credentials   Use credentials from ambient environment.
  --identity_token TOKEN      Fixed OIDC identity token to use instead of
                              obtaining credentials from OIDC flow or from the
                              environment.
  --use_staging               Use Sigstore's staging instance.
  -h, --help                  Show this message and exit.
[...]$ python -m model_signing sign sigstore
Usage: python -m model_signing sign sigstore [OPTIONS] MODEL_PATH
Try 'python -m model_signing sign sigstore -h' for help.

Error: Missing argument 'MODEL_PATH'.
```

Where the last error is because we are now in a command (rather than a
group), so we need to provide arguments, and the implicit help is no
longer supported.

Tested that the version option works:

```console
[...]$ python -m model_signing --version
python -m model_signing, version 0.2.0
```

All these tests could also be run via `hatch` directly so we don't need
to first create a wheel (via `hatch build`), install it and then run
`python -m`:

```console
[...]$ hatch run python -m model_signing --version
python -m model_signing, version 0.2.0
```

Signed-off-by: Mihai Maruseac <mihaimaruseac@google.com>