bench: avoid using heredoc in gcloud command (#554)
The GitHub Actions script is complaining about the heredoc, so just get
rid of it instead of debugging why:

	warning: here-document at line 5 delimited by end-of-file (wanted `EOF')
	ERROR: (gcloud.batch.jobs.submit) Unable to parse config file: Extra data: line 63 column 3 (char 2012)

Signed-off-by: Spencer Schrock <sschrock@google.com>